name: Preview Updater

on:
    schedule:
        -   cron: 20 2 1 * *
    workflow_dispatch:
    push:

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v5

            -   name: Update Previews
#                uses: TheDragonCode/preview-updater@main
                uses: ./
                with:
                    token: ${{ secrets.GITHUB_TOKEN || env.GITHUB_TOKEN }}
