name: Tests

on:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v6

            -   name: Use Node.js lts/*
                uses: actions/setup-node@v6
                with:
                    node-version: lts/*
                    check-latest: true

            -   run: npm ci
            -   run: npm run type-check
            -   run: npm run coverage

            -   uses: coverallsapp/github-action@master
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}

            -   run: npm run build
